<?php

/**
 * @skywalks common functions 
 *	
 */

/**
 * @skywalks common functions 
 * implement hook_help
 */
function skywalks_common_help($path, $arg) {
	switch ($path) {
		case "admin/help#skywalks_common":
		return t("skywalks common functions provides an easy to use environment seted up on your website"); 
		break; 
	}
}

function pr($var,$mode = 0){
	if (variable_get('enable_skywalks_functions') == true) {
		if ($mode == 0) {
			echo "<pre>"; 
			print_r($var);
			echo "</pre>";
		}
		elseif ($mode == 1) {
			echo "<pre>"; 
			print_r(array_keys($var));
			echo "</pre>";
		}
		else{
			echo "<pre> Unrecognised print mode </pre>";
		}
	}
	else{
		drupal_set_message(t('Error : Call to desabled function pr() . Please enable skywalks common functions to use this function by clicking <a href="admin/settings/skywalks_common">here</a>'), 'error');
	}
}

/**
 * @skywalks common blocks
 *	
 */

function skywalks_common_settings(){
	$form = array();
	$form['skywalks_settings'] = array(
		'#type' => 'fieldset',
		'#title' => 'Enable common functions',
		'#weight' => 10,
	);
	$form['skywalks_settings']['common'] = array(
		'#type' => 'checkbox',
		'#title' => t('Enable skywalks common functions'),
		'#default_value' => variable_get('enable_skywalks_functions'),
		'#cols' => 30,
		'#rows' => 5,
		'#description' => t("enable skywalks functions"),
		'#required' => FALSE,
	);
	if ((module_exists('sky_dashboard'))) {
	$form['skywalks_settings']['dashboard'] = array(
		'#type' => 'checkbox',
		'#title' => t('Enable skywalks Dashboard'),
		'#default_value' => variable_get('enable_skywalks_dashboard'),
		'#cols' => 30,
		'#rows' => 5,
		'#description' => t("enable skywalks Dashboard"),
		'#required' => FALSE,
	);
	}

	return system_settings_form($form);
}

/**
 * implements hook_menu()	
 */

function skywalks_common_menu() {
	$items['admin/settings/skywalks_common'] = array(
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('skywalks_common_settings'),
		'access arguments' => array('access sky functions'),
		'description' => 'skywalks common settings',
		'title' => 'Skywalks config',
	);
	return $items;
}

/**
 * implements hook_permission()	
 */

function skywalks_common_permission() {
	return array(
		'access sky functions' => array(
			'title' => t('Configure Sky functions'),
			'description' => t('Access and configure skywalks functions'),
		),
	);
}



/**
 * implements hook_block_info()	
 */

function skywalks_common_block_info() {
	$blocks['contact_us'] = array(
		'info' => t('Contact Form'),
	);
	return $blocks;
}

/**
 * implements hook_block_view()	
 */

function skywalks_common_block_view($delta = '') {

	$block = array();
	switch ($delta) {
		case 'contact_us':
		$block['subject'] = t('CONTAT US');
		$block['content'] = 'test';
		break;
	}
	return $block;
}

function skywalks_common_settings_validate($form, &$form_state) {
	$common = $form_state['values']['common'];
	$dashboard = $form_state['values']['dashboard'];
	variable_set('enable_skywalks_functions',$common);
	variable_set('enable_skywalks_dashboard',$dashboard);
}

function dash_access(){
	if (user_is_logged_in()) {
		return true;
	}
	else{
		drupal_goto('/user');
	}
}
