<?php
/**
 * Implements hook_block_info().
 */
function sky_dashboard_block_info() {
	$blocks['user_menu'] = array(
    // The name that will appear in the block list.
		'info' => t('user profile'),
    // Default setting.
		'cache' => DRUPAL_CACHE_PER_ROLE,
	);
	$blocks['user_graph'] = array(
    // The name that will appear in the block list.
		'info' => t('user count graph'),
    // Default setting.
		'cache' => DRUPAL_CACHE_PER_ROLE,
	);
	return $blocks;
}
/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function sky_dashboard_block_view($delta = '') {
	switch ($delta) {
		case 'user_menu':
		$block['subject'] = '';
		$block['content'] = sky_user_profile();
		break;
		case 'user_graph':
		$block['subject'] = '';
		$block['content'] = user_count_graph();
		break;
	}
	return $block;

}
/**
 * Implements hook_menu().
 * 
 * Prepares the contents of the block.
 */
function sky_dashboard_menu(){
	$items['sky/dashboard'] = array(
		'type' => MENU_NORMAL_ITEM,
		'access arguments' => array('skywalks common settings'),
		'title' => 'Dashboard',
		'description' => 'A form to mess around with.',
    	'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    	'page arguments' => array('form_example_form'), //put the name of the form here
    	'access arguments' => array('access sky dashboard'),
    	'access callback' => TRUE,
		);
	return $items;
}
function sky_user_profile(){
	global $user;
	global $base_url;
	$uid = $user->uid;
	$user = user_load($uid);
 	if (isset(($user->picture->uri))) {
		$img = file_create_url($user->picture->uri);
	}else{
		$img = $base_url."/".drupal_get_path('module', 'sky_dashboard')."/img/user.png";
	}
	$op = '
	<div style="width:300px;">
		<div class="nav-item  dropdown">
			<button class="btn btn-dark dropdown-toggle" type="button" data-toggle="dropdown">
				<i class="fa fa-user"></i>
				<span class=""></span>
			</button>
	    <ul class="dash dropdown-menu">
	    	<li class="user-li"><span href="#">'.$user->name.'</span></li>
	      <li class="drop-image"><a href="#"><img src="'.$img.'"></a></li>
	      <li class="btn-container"><a class="btn btn-outline-danger" href="/user/logout">logout</a><a class="btn btn-outline-primary" href="/user">My Accout</a></li>
	    </ul>
	  </div>
	</div>';
	return $op;
}

function form_example_form($form, &$form_state) {
  
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Click Here!'),
    '#attributes' => array('class' =>  array('element-invisible')),
  );
  
  return $form;
}

function form_example_form_validate($form, &$form_state) {
}

function form_example_form_submit($form, &$form_state) {
}

function sky_dashboard_permission() {
	return array(
		'access sky dashboard' => array(
			'title' => t('Access Sky dashboard'),
			'description' => t('Access skywalks dashboard'),
		),
	);
}

function user_count_graph(){
	$week = date("Y-m-d h:i:sa",strtotime("-1 week"));
	$month = date("Y-m-d h:i:sa",strtotime("-1 month"));
	$last_weak = strtotime($week);
	$month =  strtotime($month);

	$user_last_weaks = db_select('users', 'uid')->fields('uid')->condition('created', $last_weak,'>')->condition('status', 1,'=')->execute()->fetchAll();
	$user_last_weaks = count($user_last_weaks);

	$user_last_month = db_select('users', 'uid')->fields('uid')->condition('created', $last_weak,'>')->condition('status', 1,'=')->execute()->fetchAll();
	$user_last_month = count($user_last_month);

	$total_user = db_select('users', 'uid')->fields('uid')->condition('status', 1,'=')->execute()->fetchAll();
	$total_user = count($total_user);

	return theme(
		'user_graph', 
		array(
			'user_last_weaks' => $user_last_weaks, 
			'user_last_month' => $user_last_month,
			'total_user' => $total_user,
		)
	);
}

function sky_dashboard_theme() {
	return array(
		'user_graph' => array(
			'variables' => array(
				'user_last_weaks' => NULL,
				'user_last_month' => NULL,
				'total_user' => NULL
			),
			'template' => 'template/sky-graph',
		),
	);
}