<?php
/**
 * Implements hook_block_info().
 */
function sky_dashboard_block_info() {
	$blocks['user_menu'] = array(
    // The name that will appear in the block list.
		'info' => t('user profile'),
    // Default setting.
		'cache' => DRUPAL_CACHE_PER_ROLE,
	);
	return $blocks;
}
/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function sky_dashboard_block_view($delta = '') {
	switch ($delta) {
		case 'user_menu':
		$block['subject'] = '';
		$block['content'] = sky_user_profile();
	}
	return $block;

}
/**
 * Implements hook_menu().
 * 
 * Prepares the contents of the block.
 */
function sky_dashboard_menu(){
	$items['sky/dashboard'] = array(
		'type' => MENU_NORMAL_ITEM,
		'access arguments' => array('skywalks common settings'),
		'title' => 'Dashboard',
		'description' => 'A form to mess around with.',
    	'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    	'page arguments' => array('form_example_form'), //put the name of the form here
    	'access callback' => TRUE,
		);
	return $items;
}
function sky_user_profile(){
	global $user;
	global $base_url;
	$uid = $user->uid;
	$user = user_load($uid);
 	if (isset(($user->picture->uri))) {
		$img = file_create_url($user->picture->uri);
	}else{
		$img = $base_url."/".drupal_get_path('module', 'sky_dashboard')."/img/user.png";
	}
	$op = '<div style="width:300px;"><div class="nav-item  dropdown">
	<button class="btn btn-dark dropdown-toggle" type="button" data-toggle="dropdown"><i class="fa fa-user"></i>
	<span class=""></span></button>
	<ul class="dash dropdown-menu">
	<li class="user-li"><span href="#">'.$user->name.'</span></li>
	<li class="drop-image"><a href="#"><img src="'.$img.'"></a></li>
	<li style="margin: 20px 0px 5px;"><a class="drop-btn btn-danger" href="/user/logout">logout</a><a class="drop-btn btn-success" href="/user">My Accout</a></li>
	</ul>
	</div>
	</div>';
	return $op;
}

function form_example_form($form, &$form_state) {
  
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Click Here!'),
  );
  
  return $form;
}

function form_example_form_validate($form, &$form_state) {
}

function form_example_form_submit($form, &$form_state) {
}